Update staging-deploy.yml

diff --git a/.github/workflows/staging-deploy.yml b/.github/workflows/staging-deploy.yml
--- a/.github/workflows/staging-deploy.yml
+++ b/.github/workflows/staging-deploy.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - stg
+
 env:
   CI: false
 
@@ -14,21 +15,29 @@ jobs:
 
     steps:
       - name: Checkout repo
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
-      - name: Setup Node
-        uses: actions/setup-node@v1
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
         with:
           node-version: 20
+          cache: 'npm'
 
       - name: Install dependencies
         uses: bahmutov/npm-install@v1
 
+      - name: Ensure build directory exists
+        run: mkdir -p build
+
       - name: Build project
         run: npm run build
 
-      - name: Upload satging-ready build files
-        uses: actions/upload-artifact@v2
+      - name: Debug build output
+        run: ls -l ./build || echo "Build directory not found!"
+
+      - name: Upload staging-ready build files
+        if: success() && hashFiles('./build/**') != ''
+        uses: actions/upload-artifact@v3
         with:
           name: staging-files
           path: ./build
